name: deploy recipes

on:
  push:
    branches: [main]
    paths:
      - recipes/**
      - .github/workflows/deploy-recipes.yml
      - .github/workflows/deploy-cloudflare-worker.yml
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-cloudflare-worker.yml
    strategy:
      fail-fast: false
      matrix:
        target:
          - recipes/static-html
          - recipes/hono-api
          - recipes/hono-d1-api
          - recipes/hono-r2-api
          - recipes/cron-worker
    with:
      target: ${{ matrix.target }}
      deploy: true
      environment: CloudFlare-personal
    secrets: inherit
